site_name: Wen Jun's personal website
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    primary: teal

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@wenjunthenwj
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/wenjunthenwj/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ng-wen-jun-9549a2145/

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - 'index.md'
  - 'inspirations.md'
  - 'coin.md'
  - 'achievements.md'
  - 'leaderboard.md'

plugins:
  - search
  - table-reader

copyright: |
  &copy; 2023 <a href="https://github.com/wenjunthenwj"  target="_blank" rel="noopener">Ng Wen Jun</a>
